/**
 * Flavor tables for the NPC generator (FR10.2): names, quirks, appearances,
 * motivations. HARD RULE: every entry below is ORIGINAL writing for Safehouse —
 * never book content, never a published setting's characters (G6, §14).
 * Campaigns can override these via user-defined roll tables (FR2.11).
 */

/** ~60 full names, mixed cultures and genders. Original fiction. */
export const NAME_TABLE: readonly string[] = [
  'Kenji Marlowe',
  'Amara Okafor',
  'Dmitri Volkov',
  'Lucia Ferreira',
  'Tomás Reyes',
  'Priya Chandrasekhar',
  'Yusuf al-Rashid',
  'Mei-Lin Zhao',
  'Hana Petrova',
  'Deshawn Carter',
  'Ingrid Halvorsen',
  'Rafael Ortiz',
  'Sanaa Diallo',
  'Viktor Marsh',
  'Noor Haddad',
  'Callum O’Shea',
  'Ximena Vargas',
  'Bogdan Ilic',
  'Aiyana Redcloud',
  'Jin-Ho Pak',
  'Marisol Duarte',
  'Ezra Blackwood',
  'Katya Sorokina',
  'Themba Nkosi',
  'Siobhan Doyle',
  'Hiro Nakagawa',
  'Fatima Benali',
  'Anders Lindqvist',
  'Rosa Camacho',
  'Emeka Obi',
  'Tallulah Greaves',
  'Sergei Baranov',
  'Leilani Kahale',
  'Marcus Thorne',
  'Anouk Visser',
  'Kwame Asante',
  'Petra Novakova',
  'Diego Salcedo',
  'Yuki Amano',
  'Omar Suleiman',
  'Bridget Kavanagh',
  'Chenguang Liu',
  'Nadia Petrossian',
  'Silas Crane',
  'Adaeze Nwosu',
  'Rurik Stellan',
  'Consuelo Ibarra',
  'Takeshi Mori',
  'Zofia Wisniewska',
  'Jamal Whitfield',
  'Freya Dahl',
  'Mateo Quintana',
  'Isla MacPherson',
  'Ravi Malhotra',
  'Oksana Bondar',
  'Kofi Mensah',
  'June Okazaki',
  'Bastian Kroll',
  'Imani Sterling',
  'Wren Halloway',
];

/** ~40 one-line quirks / mannerisms. Original fiction. */
export const QUIRK_TABLE: readonly string[] = [
  'cracks each knuckle in sequence before opening any door',
  'quotes the odds out loud before every risky move',
  'keeps a dead friend’s dog tags wound around the left wrist',
  'refuses to sit with their back to a window',
  'hums old jingle tunes while reloading',
  'counts exits the moment they enter a room, lips moving',
  'never uses anyone’s real name, only invented nicknames',
  'flips a scratched casino chip across the knuckles when thinking',
  'apologizes to doors before kicking them in',
  'eats only white food off a folding chopstick set',
  'talks to their gun like it is a nervous coworker',
  'insists on shaking hands twice, once at meeting and once at parting',
  'writes every contact’s name on paper, never in a commlink',
  'laughs at exactly the wrong moments, a half-second too late',
  'chews unlit cigarettes down to the filter, never lights one',
  'salutes vending machines that work on the first try',
  'keeps an umbrella through every season and has never opened it',
  'recites building maintenance codes when nervous',
  'refuses jobs on the third of the month, no explanation given',
  'collects one bolt or screw from every site they hit',
  'whistles descending notes when a plan starts going sideways',
  'always pays in exact change, counted twice',
  'sniffs the air theatrically before pronouncing a place safe',
  'names every drone they meet and mourns the broken ones',
  'stretches like an athlete before sitting down to talk',
  'taps twice on any surface before trusting weight to it',
  'keeps a paper novel in a waterproof bag, always the same one',
  'corrects everyone’s grammar mid-firefight',
  'will not step on painted lines in parking structures',
  'sews a new button onto their jacket after every completed job',
  'addresses superiors as "boss" and everyone else as "chief"',
  'holds their breath through tunnels, even long ones',
  'files their trigger finger’s nail flat every morning',
  'swears only in dead languages picked up from trid dramas',
  'leaves a single coin balanced upright wherever they have been',
  'blinks hard twice before telling any lie',
  'drinks soykaf cold, claims hot drinks dull instinct',
  'keeps a spare glove for shaking hands with strangers',
  'measures rooms by pacing them off, even mid-conversation',
  'ends every call with "stay ugly," even to clients',
];

/** ~40 one-line appearances. Original fiction. */
export const APPEARANCE_TABLE: readonly string[] = [
  'chrome-flecked irises over a faded synthleather duster',
  'a lattice of old dermal scars laid out neat as circuit traces',
  'mirrored cybereyes and a smile that never reaches them',
  'bleached crew cut, one ear ringed in cheap silver',
  'a bulk-frame silhouette softened by a cook’s apron worn like armor',
  'rain-wet trench coat that smells of ozone and machine oil',
  'hands wrapped in fresh boxing tape, knuckles printed with faded ink',
  'a datajack behind the ear, capped with a child’s glitter sticker',
  'neon-green fiberoptic hair tied back with copper wire',
  'one polished chrome arm, the other sleeved in prayer beads',
  'a corporate-cut suit two fashion cycles old and proud of it',
  'stick-thin frame lost inside a surplus flak vest',
  'gold tooth up front, glinting when the bad ideas start',
  'burn scarring down one jaw, never hidden, never explained',
  'ancient aviator shades worn day, night, and indoors',
  'a patchwork longcoat sewn from six other coats',
  'shaved scalp mapped with a tattooed street grid of a drowned city',
  'immaculate white sneakers in a city that ruins everything white',
  'heavy brow, heavier shoulders, and a voice like gravel in a tin',
  'delicate features under a hood, eyes moving like a metronome',
  'augmented legs a size too athletic for the rest of the frame',
  'a silver-streaked braid coiled tight as a spring',
  'work jumpsuit with someone else’s name embroidered on the chest',
  'a face that photographs badly on purpose, all angle and shadow',
  'sleeve of animated tattoos, currently set to slow-falling rain',
  'a mouthful of chipped teeth from a habit of winning ugly fights',
  'rust-red utility coveralls, pockets sagging with loose tools',
  'porcelain-pale synthskin graft on the left cheek, tone slightly off',
  'compact and coiled, weight always on the balls of the feet',
  'wire-rimmed glasses with no lenses, worn for the look of it',
  'a scar that lifts one eyebrow into permanent skepticism',
  'clothes fresh from the printer, creases still sharp',
  'drum-tight braids threaded with data-bead cords',
  'a laborer’s tan ending in surgical lines at both wrists',
  'perfume expensive enough to cover the smell of gun solvent, mostly',
  'stooped tall frame that folds itself apologetically into rooms',
  'a bright enamel pin of a cartoon rat, polished daily',
  'weathered hands with a tremor that stops the instant metal touches them',
  'high-collared coat hiding a throat mic and old rope scarring',
  'grease-stained fingers with rings worn only when off the job',
];

/** ~40 one-line motivations. Original fiction. */
export const MOTIVATION_TABLE: readonly string[] = [
  'one big score away from buying a sibling out of a corp indenture',
  'pays a downtown clinic weekly to keep a parent breathing',
  'wants a name feared enough that no one checks the ledger behind it',
  'saving for a fishing boat and a coastline nobody shoots over',
  'owes a syndicate lieutenant who never forgets a decimal',
  'collects proof against a mid-tier exec, one file at a time',
  'runs the shadows to keep a talented kid from having to',
  'believes the district was stolen block by block and keeps receipts',
  'needs the next job because standing still feels like drowning',
  'funding a night-school diploma under a clean fake identity',
  'wants their old squad’s betrayer found before growing old',
  'keeps a safehouse stocked for strays and pays for it in blood money',
  'chasing the courier who vanished with their only clean SIN',
  'sworn to put a certain clinic chain out of business for good',
  'stacking cash for black-market surgery a corp policy refused',
  'wants to be the person their probation officer swore they never would',
  'feeding a gambling habit that always sits down at the wrong tables',
  'protects the block’s street kids and pretends it is just business',
  'buying back a family heirloom pawned in a very bad winter',
  'trying to retire before the implants need refinancing',
  'hunting the designer of a virus that bricked a loved one’s cyberlimbs',
  'wants a bar of their own with their name misspelled in neon',
  'works off a debt inherited from a parent’s failed franchise',
  'stockpiling favors like ammunition for a war only they see coming',
  'keeping a promise made over a hospital bed, details never shared',
  'wants out of the sprawl before the next crackdown, any exit will do',
  'building a pension one dangerous errand at a time',
  'proving a point to an academy that washed them out on politics',
  'needs money fast; the reason changes but the deadline never does',
  'funding an unlicensed orbital dream one payload at a time',
  'wants revenge served through paperwork, audits, and ruin',
  'pays tribute to stay invisible and hates every payment more',
  'searching crowds for a face from a photograph kept folded in a boot',
  'keeps three go-bags packed and dreams nightly of using none of them',
  'wants the neighborhood’s water clean and knows who dirtied it',
  'saving a bounty for the day their own file crosses a fixer’s desk',
  'chasing the high of the one job that went perfectly, years back',
  'supports two households that must never learn of each other',
  'wants to matter in a city built to prove nobody does',
  'plans to disappear beautifully and tip every bartender on the way out',
];
