/**
 * Vendor pdf.js into `apps/web/public/pdfjs/` (DESIGN.md §13: "pdf.js,
 * self-hosted … no external viewer, no CDN").
 *
 * The reader loads pdf.js as a plain ES module from our own origin rather than
 * bundling it, for three reasons:
 *
 *  - **The library never touches the bundle.** §15 budgets initial JS at
 *    < 500 KB gz; pdf.js plus its worker is several times that. Served as a
 *    static asset it costs zero bytes until a ref chip is tapped.
 *  - **The worker stays a worker.** pdf.js wants a same-origin module worker
 *    URL; a copied file is exactly that, with no bundler-specific plumbing.
 *  - **A missing library degrades instead of failing the build.** If this
 *    script has not run, the dynamic import rejects at runtime and the reader
 *    falls back to the browser's own viewer (see `features/reader/pdfjs.ts`).
 *    That is also why this script never exits non-zero: it must not be able to
 *    turn `pnpm -r build` red.
 *
 * Run automatically from `postinstall` and from `build`; by hand with
 * `pnpm --filter @safehouse/web vendor:pdfjs`.
 */
import { createRequire } from 'node:module';
import { cpSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const WEB_ROOT = fileURLToPath(new URL('..', import.meta.url));
const DEST = join(WEB_ROOT, 'public', 'pdfjs');

/** Prefer the transpiled build: §15 targets a three-year-old phone. */
const BUILD_DIRS = ['legacy/build', 'build'];
const MAIN_CANDIDATES = ['pdf.min.mjs', 'pdf.mjs'];
const WORKER_CANDIDATES = ['pdf.worker.min.mjs', 'pdf.worker.mjs'];

function warn(message) {
  console.warn(`[vendor-pdfjs] ${message}`);
}

function pdfjsRoot() {
  try {
    const require = createRequire(import.meta.url);
    return dirname(require.resolve('pdfjs-dist/package.json'));
  } catch {
    return null;
  }
}

/** First existing file among `names` inside `dir`. */
function pick(dir, names) {
  for (const name of names) {
    const path = join(dir, name);
    if (existsSync(path)) return path;
  }
  return null;
}

/** Copy only when the destination is missing or a different size. */
function copyFile(from, to) {
  try {
    if (existsSync(to) && statSync(to).size === statSync(from).size) return false;
    cpSync(from, to);
    return true;
  } catch (err) {
    warn(`could not copy ${from}: ${String(err)}`);
    return false;
  }
}

function copyDir(from, to) {
  try {
    if (!existsSync(from)) return false;
    if (existsSync(to)) return false; // versioned by the install; never stale alone
    cpSync(from, to, { recursive: true });
    return true;
  } catch (err) {
    warn(`could not copy ${from}: ${String(err)}`);
    return false;
  }
}

function main() {
  const root = pdfjsRoot();
  if (!root) {
    warn('pdfjs-dist is not installed — the reader will use the browser viewer.');
    return;
  }

  let version = 'unknown';
  try {
    version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version ?? 'unknown';
  } catch {
    // not fatal
  }

  const buildDir = BUILD_DIRS.map((d) => join(root, d)).find((d) => existsSync(d));
  if (!buildDir) {
    warn(`pdfjs-dist ${version} has no recognisable build directory.`);
    return;
  }
  const main_ = pick(buildDir, MAIN_CANDIDATES);
  const worker = pick(buildDir, WORKER_CANDIDATES);
  if (!main_ || !worker) {
    warn(`pdfjs-dist ${version}: could not find the ESM build and its worker.`);
    return;
  }

  mkdirSync(DEST, { recursive: true });
  // The vendored tree is generated output; keep it out of git without touching
  // the repo-root .gitignore (git honours a nested one even when it is ignored).
  writeFileSync(
    join(DEST, '.gitignore'),
    '# Generated by apps/web/scripts/vendor-pdfjs.mjs — do not commit.\n*\n',
  );

  copyFile(main_, join(DEST, 'pdf.mjs'));
  copyFile(worker, join(DEST, 'pdf.worker.mjs'));
  // CMaps and the base-14 fonts are fetched over HTTP by pdf.js when a book
  // needs them. Absent, it warns and substitutes; present, the page is right.
  copyDir(join(root, 'cmaps'), join(DEST, 'cmaps'));
  copyDir(join(root, 'standard_fonts'), join(DEST, 'standard_fonts'));

  console.log(`[vendor-pdfjs] pdf.js ${version} vendored to public/pdfjs/`);
}

try {
  main();
} catch (err) {
  // Never fail the build over the fallback-able half of a feature.
  warn(`skipped: ${String(err)}`);
}
