/**
 * Character creation (FR3.9, docs/CHARGEN.md §8.4): the book's numbers as
 * data — skills, metatypes, the priority table, creation levels, advancement
 * costs, implant grades, foci, traditions, lifestyles and the quality
 * whitelist. Pure, no I/O; numbers, ids and page refs, no book text.
 *
 * Explicit re-exports keep the package surface deliberate and clear of the
 * names the root barrel already carries (`SkillGroup`, `ATTR_MAX`,
 * `SKILL_MAX`, `BondedFocus`, …) and of the vocabularies `@safehouse/contracts`
 * owns (`PriorityLevel`, `PriorityTable`, `CreationLevel`, `MagicKind`,
 * `KnowledgeCategory`, `AugmentGrade`, `MagicTradition`, `LifestyleTier`):
 * these tables are keyed by those enums and import them, never redefine them.
 */
export {
  ACTIVE_SKILL_IDS,
  ACTIVE_SKILL_TABLE,
  ACTIVE_SKILL_BY_ID,
  SKILL_GROUP_IDS,
  SKILL_GROUP_TABLE,
  SKILL_GROUP_BY_ID,
  MAGICAL_SKILL_GROUP_IDS,
  KNOWLEDGE_CATEGORY_TABLE,
  LANGUAGE_SKILL,
  CREATION_SKILL_RULES,
  freeKnowledgePoints,
  activeSkillRow,
  skillGroupRow,
  type ActiveSkillId,
  type ActiveSkillRow,
  type SkillGroupId,
  type SkillGroupRow,
  type SkillCategory,
  type SkillRestriction,
  type KnowledgeCategoryRow,
} from './skills.js';
export {
  METATYPE_ATTRIBUTES,
  BUILD_ATTRIBUTE_NAMES,
  CORE_METATYPE_IDS,
  METATYPE_IDS,
  RACIAL_TRAIT_IDS,
  METATYPE_TABLE,
  METATYPE_BY_ID,
  CREATION_ATTRIBUTE_RULES,
  metatypeRow,
  specialPointsFor,
  metatypeKarmaFor,
  hasRacialTrait,
  type MetatypeAttribute,
  type AttributeRange,
  type MetatypeFamily,
  type CoreMetatypeId,
  type MetatypeId,
  type RacialTraitId,
  type RacialTrait,
  type MetatypePriorityCell,
  type MetatypeRow,
} from './metatypes.js';
export {
  PRIORITY_CHARTS,
  MAGIC_KIND_TABLE,
  SUM_TO_TEN,
  magicPriorityOption,
  magicRowOffers,
  grantPoolIncludes,
  type PriorityChart,
  type PriorityRow,
  type MagicKindRow,
  type MagicPriorityOption,
  type GrantPool,
  type SkillGrant,
  type GroupGrant,
} from './priority.js';
export {
  BOOK_QUALITY_CAP,
  CREATION_LEVEL_PRESETS,
  CREATION_CONTACT_RULES,
  type CreationLevelPreset,
} from './levels.js';
export {
  KARMA_COSTS,
  TRAINING_MODIFIERS,
  DOWNTIME_LIMITS,
  karmaForAttribute,
  karmaForActiveSkill,
  karmaForSkillGroup,
  karmaForKnowledgeSkill,
  INITIATION_REFS,
  karmaForInitiation,
  karmaForQualityInPlay,
  karmaForQualityBuyOff,
  trainingTime,
  type TrainingKind,
  type TrainingUnit,
  type TrainingTime,
} from './costs.js';
export { IMPLANT_GRADES, CREATION_GRADE_REF, type ImplantGradeRow } from './grades.js';
export {
  FOCUS_TYPE_IDS,
  FOCUS_TYPES,
  FOCUS_SUBTYPES,
  FOCUS_LIMITS,
  focusBondingKarma,
  focusTypeOf,
  focusTypesOf,
  focusSpendType,
  type FocusType,
  type FocusTypeRow,
} from './foci.js';
export {
  TRADITIONS,
  SPIRIT_TYPE_IDS,
  SPIRIT_TYPES_REF,
  SPRITE_TYPE_IDS,
  SPRITE_TYPES_REF,
  SPELL_CATEGORY_IDS,
  type TraditionRow,
  type SpiritTypeId,
  type SpriteTypeId,
  type SpellCategoryId,
} from './traditions.js';
export {
  LIFESTYLES,
  LIFESTYLE_METATYPE_REF,
  lifestyleRow,
  lifestyleMultiplierFor,
  startingNuyenFor,
  type LifestyleRow,
} from './lifestyles.js';
export {
  QUALITY_RULE_IDS,
  QUALITY_RULES,
  QUALITY_RULE_BY_ID,
  RACIAL_QUALITY_TRAITS,
  normalizeQualityName,
  qualityRuleFor,
  isQualityBuyOff,
  bornQualities,
  racialQualities,
  qualityRatingRange,
  qualityKarmaFor,
  type QualityRatingLevel,
  type QualityRatingRange,
  type QualityRuleId,
  type QualityRule,
  type QualityRuleEntry,
  type DoubledCostScope,
  type LifestyleSurchargeLevel,
} from './qualityRules.js';

// ---------------------------------------------------------------------------
// The logic over those tables: ratings, budgets, validation, the walkthrough's
// steps, compile, Karma spends, and reading a catalogue row's numbers
// (docs/CHARGEN.md §4.2, §8.4).
// ---------------------------------------------------------------------------
export {
  emptyBuild,
  clearSpend,
  setPriority,
  setMethod,
  setMetatype,
  setMagicKind,
  setAttributePoints,
  setSpecialPoints,
  powerPointsBought,
  setPowerPointsBought,
} from './build.js';
export {
  effectiveTables,
  qualityEffects,
  qualityRatingOf,
  ratings,
  type EffectiveTables,
  type HeldQuality,
  type QualityEffects,
  type AttributeRating,
  type SkillRating,
  type GroupRating,
  type KnowledgeRating,
  type LanguageRating,
  type BuildRatings,
} from './ratings.js';
export {
  budgets,
  tallyBuild,
  buildPricing,
  parseAvailability,
  purchaseAvailability,
  purchaseCost,
  purchaseEssence,
  purchaseDeviceRating,
  lifestyleMonthlyCost,
  startingLifestyle,
  formulaGroup,
  focusPurchaseMatches,
  knowsFormulaGroup,
  castsSpells,
  summonsSpirits,
  usesMagic,
  usesResonance,
  isBioware,
  isDevice,
  type BuildTally,
  type AvailabilityStatus,
  type ParsedAvailability,
} from './budget.js';
export {
  ELIGIBILITY_REFS,
  eligibilityContext,
  eligibilityMessage,
  skillEligibility,
  groupEligibility,
  skillEligibilityIn,
  groupEligibilityIn,
  type Eligibility,
  type EligibilityCode,
  type EligibilityContext,
  type EligibilityReason,
} from './eligibility.js';
export {
  catalogueQualityPrice,
  catalogueQualityKarma,
  cataloguePowerPoints,
  catalogueWareFigures,
  type CatalogueQualityPrice,
  type QualityKarmaChoice,
  type CataloguePowerPoints,
  type CatalogueWareRow,
  type CatalogueWareOptions,
  type CatalogueWareFigures,
} from './catalogue.js';
export { validate, issueRule, ISSUE_RULES, type IssueRule, type IssueCode } from './validate.js';
export { stepStatus, type StepStatus } from './steps.js';
export {
  compileBuild,
  type CompiledBuild,
  type CompiledContact,
  type CompiledSpirit,
  type CompiledSprite,
  type CompiledFocus,
  type CompiledLifestyle,
  type CompiledOpening,
  type CompileOptions,
} from './compile.js';
export {
  karmaCostOf,
  trainingTimeOf,
  applySpend,
  spendKarma,
  costDoubling,
  doublesSkill,
  doublesGroup,
  doublesKnowledge,
  doublesSpecialization,
  ADVANCE_LABEL_MAX,
  ADVANCE_REFS,
  MAX_TRAINING_STEPS,
  PLAY_SKILL_RULES,
  advanceLabel,
  advanceKey,
  advanceCurrentRating,
  advanceRefusals,
  attributeMaxInPlay,
  effectiveSpecial,
  groupStanding,
  playFacts,
  playMagicKind,
  quoteAdvance,
  skillMaxInPlay,
  specialAttributeLoss,
  trainingPhrase,
  type AdvanceCheckOptions,
  type AdvanceNote,
  type AdvanceQuote,
  type AdvanceRefusal,
  type AdvanceRefusalCode,
  type ApplySpendOptions,
  type CostDoubling,
  type DoublingQuality,
  type GroupStanding,
  type PlayFacts,
  type SpendPricing,
  type SpendSheet,
  type SpendTraining,
  type TrainingOptions,
} from './advance.js';
export {
  CONCEPT_IDS,
  BLANK_CONCEPT_ID,
  CONCEPT_GEAR_KINDS,
  CONCEPT_GEAR_LISTS,
  CONCEPT_PRESETS,
  CONCEPT_PRESET_BY_ID,
  conceptPreset,
  applyConcept,
  type ConceptId,
  type ConceptGearKind,
  type ConceptGearSlot,
  type ConceptSkill,
  type ConceptGroup,
  type ConceptKnowledge,
  type ConceptLanguage,
  type ConceptMagic,
  type ConceptSpend,
  type ConceptPreset,
  type ApplyConceptOptions,
} from './concepts.js';
