/**
 * Fixer data layer (M12): chat send (streams back over WS as `fixer.*`
 * ephemerals), drafts inbox over `ai_generations` (FR12.15), and the
 * 503 `ai_disabled` detection (NG7: no LLM_BASE_URL → features hide).
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { ApiError, apiGet, apiPost, queryClient } from '../../../api/client.js';

/** True when the server said AI is off (503 ai_disabled). */
export function isAiDisabled(err: unknown): boolean {
  return err instanceof ApiError && err.status === 503 && err.code === 'ai_disabled';
}

/**
 * AI availability (NG7 / FR12.13): with no `LLM_BASE_URL` the server answers
 * 503 `ai_disabled` and every AI entry point goes quiet. GET /api/fixer/status
 * is the cheap probe, so the UI never has to fail a send to find out.
 */
export interface FixerStatus {
  enabled: boolean;
  models: { primary: string; fast: string } | null;
  /** Cap on tool rounds per turn (FR12.17). */
  maxToolRounds?: number;
}

export function useFixerStatus() {
  return useQuery({
    queryKey: ['fixer', 'status'],
    queryFn: () => apiGet<FixerStatus>('/api/fixer/status'),
    retry: 0,
    staleTime: 60_000,
  });
}

/** True when status/send/drafts told us the Fixer is off (503 ai_disabled). */
export function aiDisabledFrom(status: FixerStatus | undefined, ...errors: unknown[]): boolean {
  if (status && status.enabled === false) return true;
  return errors.some(isAiDisabled);
}

export interface FixerChatBody {
  campaignId: string;
  message: string;
  conversationId?: string;
  /** Model slot hint (FR12.16): 'primary' | 'fast'. */
  slot?: 'primary' | 'fast';
}

/** The turn also streams over WS as `fixer.*` ephemerals; this is the result. */
export interface FixerChatAck {
  conversationId?: string;
  text?: string;
  rounds?: number;
  truncated?: boolean;
  tools?: unknown[];
  usage?: { promptTokens?: number; completionTokens?: number; totalTokens?: number };
  model?: string;
  snapshotApplied?: boolean;
}

export function useFixerSend() {
  return useMutation({
    mutationFn: (body: FixerChatBody) => apiPost<FixerChatAck>('/api/fixer/chat', body),
  });
}

/** An `ai_generations` row (§9.2) — Principle 8's paper trail. */
export interface AiGeneration {
  id: string;
  campaignId?: string;
  kind: string;
  /** Entity ref the draft targets, e.g. { type: 'npc_template', id } — shape loose. */
  target?: unknown;
  prompt?: string;
  model?: string;
  output?: unknown;
  status: 'draft' | 'accepted' | 'rejected';
  usage?: { promptTokens?: number; completionTokens?: number; totalTokens?: number; latencyMs?: number };
  createdAt?: string;
  /**
   * Spoiler-guard flags (FR12.19): GM-only facts the draft drew on. Read via
   * `spoilerFlagsOf`, which also looks inside `output` — where a draft
   * generated by a tool round tends to carry them.
   *
   * The server sends `SpoilerFlag` objects (`{name, why}`); this was declared
   * `string[]` once, which made a filter that dropped every real flag look
   * correct and left the GM's card silently unwarned. Both shapes are typed
   * and handled.
   */
  spoilerFlags?: (string | { name?: string; why?: string })[];
}

export function useDrafts(campaignId: string) {
  return useQuery({
    queryKey: ['campaign', campaignId, 'generations', 'draft'],
    queryFn: async () =>
      (
        await apiGet<{ generations: AiGeneration[] }>(
          `/api/campaigns/${campaignId}/generations?status=draft`,
        )
      ).generations,
    enabled: Boolean(campaignId),
    retry: 0,
    refetchInterval: 20_000,
  });
}

const invalidateDrafts = (campaignId: string) => () => {
  void queryClient.invalidateQueries({ queryKey: ['campaign', campaignId, 'generations'] });
};

export function useAcceptDraft(campaignId: string) {
  return useMutation({
    /** POST /api/generations/:id/accept (§12); optional edited output travels along. */
    mutationFn: ({ id, output }: { id: string; output?: unknown }) =>
      apiPost<unknown>(`/api/generations/${id}/accept`, output !== undefined ? { output } : undefined),
    onSuccess: invalidateDrafts(campaignId),
  });
}

export function useRejectDraft(campaignId: string) {
  return useMutation({
    mutationFn: (id: string) => apiPost<unknown>(`/api/generations/${id}/reject`),
    onSuccess: invalidateDrafts(campaignId),
  });
}

/**
 * Pull spoiler-guard flags off a draft wherever the server put them.
 *
 * The server sends `SpoilerFlag[]` (`{name, why}`) — an earlier client kept
 * only `typeof f === 'string'`, which silently discarded every object flag and
 * left the GM accepting a player-facing draft with no warning on the card
 * (FR12.19). Both shapes are accepted: the string form for anything still
 * sending one, the object form rendered as its name.
 */
export function spoilerFlagsOf(gen: AiGeneration): string[] {
  const normalise = (flags: unknown): string[] =>
    Array.isArray(flags)
      ? flags
          .map((f) => {
            if (typeof f === 'string') return f;
            if (typeof f === 'object' && f !== null) {
              const name = (f as Record<string, unknown>)['name'];
              if (typeof name === 'string' && name.length > 0) return name;
            }
            return '';
          })
          .filter((f) => f.length > 0)
      : [];

  const direct = normalise(gen.spoilerFlags);
  if (direct.length > 0) return direct;

  const out = gen.output;
  if (typeof out === 'object' && out !== null) {
    const o = out as Record<string, unknown>;
    return normalise(o['spoilerFlags'] ?? o['spoilers']);
  }
  return [];
}

/** Best-effort plain-text rendering of a draft's output for the editor. */
export function draftOutputText(gen: AiGeneration): string {
  const out = gen.output;
  if (typeof out === 'string') return out;
  if (typeof out === 'object' && out !== null) {
    const o = out as Record<string, unknown>;
    for (const key of ['text', 'markdown', 'content']) {
      if (typeof o[key] === 'string') return o[key];
    }
    return JSON.stringify(out, null, 2);
  }
  return '';
}
